using UnityEngine;
using System.Collections;

public class ItemManager : MonoBehaviour
{
    [Header("Components")]
    public OllamaClient ollamaClient;
    public PlayerStats playerStats;

    [Header("Skill System")]
    public SkillManager skillManager;
    void Start()
    {
        if (ollamaClient == null)
        {
            ollamaClient = GetComponent<OllamaClient>();
        }
    }

    public void UseItem(ItemData item)
    {
        if (item == null)
        {
            Debug.LogWarning("UseItem called with null item.");
            return;
        }

        StartCoroutine(ApplyItem(item));
    }

    IEnumerator ApplyItem(ItemData item)
    {
        Debug.Log($"=== Applying Item: {item.itemName} ===");

        bool isComplete = false;
        AIResponse aiResponse = null;
        string errorMessage = null;

        yield return ollamaClient.GenerateSkillsAndStats(
            item,
            response =>
            {
                aiResponse = response;
                isComplete = true;
            },
            error =>
            {
                errorMessage = error;
                isComplete = true;
            }
        );

        yield return new WaitUntil(() => isComplete);

        if (errorMessage != null)
        {
            Debug.LogError($"Failed to generate AI content: {errorMessage}");
            yield break;
        }

        if (aiResponse != null)
        {
            ApplyStatModel(aiResponse.stat_model);
            ApplySkillModel(aiResponse.skill_model);
        }
    }

    void ApplyStatModel(StatModel statModel)
    {
        Debug.Log("=== Applying Stat Model ===");

        Stats statChanges = new Stats
        {
            Speed = statModel.stat_changes.Speed,
            Attack = statModel.stat_changes.Attack,
            Defense = statModel.stat_changes.Defense,
            Jump = statModel.stat_changes.Jump,
            Attack_Speed = statModel.stat_changes.Attack_Speed,
            Range = statModel.stat_changes.Range
        };

        playerStats.ModifyStats(statChanges, statModel.duration_seconds);
    }

    void ApplySkillModel(SkillModel skillModel)
    {
        Debug.Log("=== Applying Skill Model ===");

        if (skillModel == null)
        {
            Debug.LogWarning("Skill model is null!");
            return;
        }

        if (skillModel.new_skills == null || skillModel.new_skills.Count == 0)
        {
            Debug.LogWarning("No skills generated by AI!");
            return;
        }

        if (skillManager != null)
        {
            skillManager.ClearSkills();
        }

        foreach (var skill in skillModel.new_skills)
        {
            Debug.Log($"New Skill: {skill.name}");
            Debug.Log($"  Sequence: {string.Join(" -> ", skill.sequence)}");
            Debug.Log($"  Description: {skill.description}");
            Debug.Log($"  Cooldown: {skill.cooldown}s, Duration: {skill.duration}s");

            if (skillManager != null)
            {
                skillManager.AddSkill(skill);
            }
        }
    }
}
