using System;
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "OllamaSettings", menuName = "LLM/Ollama Settings")]
public class OllamaSettings : ScriptableObject
{
    [Header("Basic Settings")]
    public string model = "deepseek-r1:7b";
    public string format;
    public bool stream = false;
    public string keepAlive = null;

    [TextArea(3, 20)]
    [Tooltip("System prompt template; supports {{varName}} placeholders.")]
    public string systemPromptTemplate;

    [TextArea(3, 20)]
    [Tooltip("Example JSON output used by the analyzer to infer produced keys.")]
    public string jsonOutputFormat = "{\"answer\":\"\"}";

    [Serializable]
    public class ModelParams
    {
        public float temperature = 0.7f;
        public float top_p = 0.9f;
        public float top_k = 40f;
        public int num_predict = 0;
        public float repeat_penalty = 1.1f;
    }

    public ModelParams modelParams = new ModelParams();

    [NonSerialized]
    private string _lastRenderedPrompt;

    /// <summary>
    /// Renders the system prompt with the given state dictionary and stores the result for later reuse.
    /// </summary>
    public void RenderSystemPrompt(Dictionary<string, string> state)
    {
        var tmpl = new PromptTemplate(systemPromptTemplate ?? string.Empty);
        _lastRenderedPrompt = tmpl.Render(state);
    }

    /// <summary>
    /// Returns the most recently rendered prompt that was generated by RenderSystemPrompt.
    /// </summary>
    public string GetLastRenderedPrompt()
    {
        return _lastRenderedPrompt;
    }
}
