using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;

[CreateAssetMenu(fileName = "OllamaSettings", menuName = "LLM/Ollama Settings")]
public class OllamaSettings : ScriptableObject
{
    [Header("Basic Settings")]
    public string model = "gemma3:4b-it-qat";
    public string format;
    public bool stream = false;
    public string keepAlive = null;

    [TextArea(3, 20)]
    [Tooltip("System prompt template; supports {{varName}} placeholders.")]
    public string systemPromptTemplate;

    [SerializeField]
    [Tooltip("Structured definition that drives the JSON format enforced at runtime.")]
    private List<JsonFieldDefinition> jsonFields = new();

    [Serializable]
    public class ModelParams
    {
        public float temperature = 0.7f;
        public float top_p = 0.9f;
        public float top_k = 40f;
        public int num_predict = 0;
        public float repeat_penalty = 1.1f;
    }

    public ModelParams modelParams = new ModelParams();

    [NonSerialized]
    private string _lastRenderedPrompt;

    public IReadOnlyList<JsonFieldDefinition> JsonFields => jsonFields;

    private void OnValidate()
    {
        jsonFields ??= new List<JsonFieldDefinition>();
        RebuildFormatFromFields();
    }

    /// <summary>
    /// Forces the format string to match the structured JSON field definitions.
    /// </summary>
    public void RebuildFormatFromFields()
    {
        format = JsonFieldDefinition.BuildSchema(jsonFields);
    }

    /// <summary>
    /// Renders the system prompt with the given state dictionary and stores the result for later reuse.
    /// </summary>
    public void RenderSystemPrompt(Dictionary<string, string> state)
    {
        var tmpl = new PromptTemplate(systemPromptTemplate ?? string.Empty);
        _lastRenderedPrompt = tmpl.Render(state);
    }

    /// <summary>
    /// Returns the most recently rendered prompt that was generated by RenderSystemPrompt.
    /// </summary>
    public string GetLastRenderedPrompt()
    {
        return _lastRenderedPrompt;
    }
}

[Serializable]
public class JsonFieldDefinition
{
    public string fieldName = "field";
    public JsonFieldType fieldType = JsonFieldType.String;
    public JsonArrayElementType arrayElementType = JsonArrayElementType.String;
    [SerializeField]
    public List<JsonFieldDefinition> children = new();
    [SerializeField]
    public List<string> enumOptions = new();
    [SerializeField]
    public string minValue;
    [SerializeField]
    public string maxValue;

    public static string BuildSchema(List<JsonFieldDefinition> fields)
    {
        if (fields == null || fields.Count == 0)
        {
            return string.Empty;
        }

        var root = BuildObjectSchema(fields);
        return root?.ToString(Formatting.None) ?? string.Empty;
    }

    private static JObject BuildObjectSchema(List<JsonFieldDefinition> fields)
    {
        if (fields == null || fields.Count == 0)
        {
            return null;
        }

        var properties = new JObject();
        var required = new JArray();

        foreach (var field in fields)
        {
            if (field == null || string.IsNullOrWhiteSpace(field.fieldName))
            {
                continue;
            }

            var schema = BuildSchemaForField(field);
            if (schema == null)
            {
                continue;
            }

            properties[field.fieldName] = schema;
            required.Add(field.fieldName);
        }

        if (!properties.HasValues)
        {
            return null;
        }

        var obj = new JObject
        {
            ["type"] = "object",
            ["properties"] = properties,
            ["required"] = required
        };
        obj["additionalProperties"] = false;
        return obj;
    }

    private static JObject BuildSchemaForField(JsonFieldDefinition field)
    {
        JObject schema;
        switch (field.fieldType)
        {
            case JsonFieldType.Object:
                schema = BuildObjectSchema(field.children) ?? new JObject { ["type"] = "object" };
                break;
            case JsonFieldType.Array:
                schema = new JObject { ["type"] = "array" };
                schema["items"] = field.arrayElementType == JsonArrayElementType.Object
                    ? BuildObjectSchema(field.children) ?? new JObject { ["type"] = "object" }
                    : new JObject { ["type"] = field.GetArrayItemKeyword() };
                break;
            default:
                schema = new JObject { ["type"] = field.GetTypeKeyword() };
                break;
        }

        var enums = NormalizeEnums(field.enumOptions);
        if (enums.Count > 0)
        {
            schema["enum"] = new JArray(enums);
        }
        else if (field.fieldType == JsonFieldType.Object)
        {
            schema["additionalProperties"] = false;
        }

        AppendNumericBounds(schema, field);

        return schema;
    }

    private string GetTypeKeyword()
    {
        return fieldType switch
        {
            JsonFieldType.String => "string",
            JsonFieldType.Number => "number",
            JsonFieldType.Integer => "integer",
            JsonFieldType.Boolean => "boolean",
            JsonFieldType.Object => "object",
            JsonFieldType.Array => "array",
            _ => "string"
        };
    }

    private string GetArrayItemKeyword()
    {
        return arrayElementType switch
        {
            JsonArrayElementType.String => "string",
            JsonArrayElementType.Number => "number",
            JsonArrayElementType.Integer => "integer",
            JsonArrayElementType.Boolean => "boolean",
            JsonArrayElementType.Object => "object",
            _ => "string"
        };
    }

    private static List<string> NormalizeEnums(List<string> enums)
    {
        if (enums == null)
        {
            return new List<string>();
        }

        return enums
            .Where(e => !string.IsNullOrWhiteSpace(e))
            .Select(e => e.Trim())
            .Distinct(StringComparer.Ordinal)
            .ToList();
    }

    private static void AppendNumericBounds(JObject schema, JsonFieldDefinition field)
    {
        if (schema == null || field == null)
        {
            return;
        }

        bool isNumeric = field.fieldType == JsonFieldType.Number || field.fieldType == JsonFieldType.Integer;
        if (!isNumeric)
        {
            return;
        }

        if (double.TryParse(field.minValue, NumberStyles.Any, CultureInfo.InvariantCulture, out double min))
        {
            schema["minimum"] = min;
        }

        if (double.TryParse(field.maxValue, NumberStyles.Any, CultureInfo.InvariantCulture, out double max))
        {
            schema["maximum"] = max;
        }
    }
}

public enum JsonFieldType
{
    String = 0,
    Number = 1,
    Integer = 2,
    Boolean = 3,
    Object = 4,
    Array = 5
}

public enum JsonArrayElementType
{
    String = 0,
    Number = 1,
    Integer = 2,
    Boolean = 3,
    Object = 4
}
